---
- name: Configure Ubuntu for K8s
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true

  tasks:
  - name: Update package cache
    apt: 
      update_cache: yes

  - name: Install Raspberry Pi EEPROM update package
    apt:
      name: rpi-eeprom
      state: latest

  - name: Display Raspberry Pi EEPROM status
    command: rpi-eeprom-update
    register: eeprom
    ignore_errors: true
  - debug: var=eeprom.stdout_lines

  - name: Upgrade all packages, full-upgrade
    apt:
      upgrade: full

  - name: Reboot and wait
    reboot:
      reboot_timeout: 300

  - name: Display Raspberry Pi EEPROM status
    command: rpi-eeprom-update
    register: eeprom
  - debug: var=eeprom.stdout_lines
