---
- name: Bootstrap SSH
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_pass: ubuntu

  tasks:
  - name: Deploy SSH key
    authorized_key: 
      user: ubuntu
      state: present
      key: "{{ lookup('file', 'id_rsa.pub') }}"

  - name: Allow 'sudo' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Disable password login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify:
      - restart sshd

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted

- name: Configure Ubuntu for K8s
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true

  tasks:
  - name: Update package cache
    apt: 
      update_cache: yes

  - name: Install Raspberry Pi EEPROM update package
    apt:
      name: rpi-eeprom
      state: latest

  - name: Display Raspberry Pi EEPROM status
    command: rpi-eeprom-update
    register: eeprom
  - debug: var=eeprom.stdout_lines

  - name: Upgrade all packages, full-upgrade
    apt:
      upgrade: full

  - name: Reboot and wait
    reboot:
      reboot_timeout: 3600

  - name: Display Raspberry Pi EEPROM status
    command: rpi-eeprom-update
    register: eeprom
  - debug: var=eeprom.stdout_lines
