all:
    hosts:
        # 192.168.20.50:
        #     vars: 
        #         hostname: rpi4-01
        192.168.20.51:
            vars: 
                hostname: rpi4-02
    vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o userknownhostsfile=/dev/null'
        