all:
    vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o userknownhostsfile=/dev/null'
    children:
        master:
            hosts:
                192.168.16.50:
                    hostname: rpi4-01
        nodes:
            hosts:
                192.168.16.51:
                    hostname: rpi4-02
                192.168.16.52:
                    hostname: rpi4-03
                192.168.16.53:
                    hostname: rpi4-04
                192.168.16.54:
                    hostname: rpi4-05
        