apiVersion: v1
kind: Namespace
metadata:
  name: kube-verify
  labels:
    name: kube-verify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-verify
  namespace: kube-verify
  labels:
    app: kube-verify
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kube-verify
  template:
    metadata:
      labels:
        app: kube-verify
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.4-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kube-verify
  namespace: kube-verify
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: kube-verify
  type: LoadBalancer